### ISSUE TITLE
Work on mobile views for new pages

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight.io#282]

**Comment by julian-highlight** [comment]
Got an update here for the Homepage! 
https://www.figma.com/file/lsi5qUTKAKxLv4VQ9K3cDJ/Highlight-%E2%80%93-Site-Build?node-id=3885%3A28109&t=OBIGLkKUNVatiY0W-11 @jay-khatri 

fyi @Abhishek-More

**Comment by jay-khatri** [comment]
thanks julian, marking as done.
