### ISSUE TITLE
Updates to "breadcrumbs" & links in docs pages

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight.io#406]
## Task 1: links to headings

For our docs, we don't render the `index.md` doc in the left panel by design. For example, there is no way to get to https://www.highlight.io/docs/general/company from the left sidebar here:

![Image](https://user-images.githubusercontent.com/20292680/223285189-647485b3-b8ea-4830-a14c-64f0d3cf673f.png)

However, by clicking the [link](https://www.highlight.io/docs/general/company), the page still exists. 

We should handle this by redirecting this ^ link to the first child of the heading. In this case, we should redirect https://www.highlight.io/docs/general/company to https://www.highlight.io/docs/general/company/values.

## Task 2: breadcrumbs
As a second step, we should make these breadcrumbs clickable. Given the above change, this will mean that clicking on "Company" and "Mission & Values" should take you to the same place. 

![Image](https://user-images.githubusercontent.com/20292680/223285652-13363164-6ee9-4b0a-8d31-0aae16381a26.png)

**Comment by jay-khatri** [comment]
cc @ccschmitz if you have anything to add. Thanks for reminding of this today.

**Comment by ccschmitz** [comment]
> We should handle this by redirecting this ^ link to the first child of the heading. In this case, we should redirect https://www.highlight.io/docs/general/company to https://www.highlight.io/docs/general/company/values.

Might be worth trying to hide these in our search results as well, otherwise we show a few options for language/framework searches and it's not clear where to start.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/308182/223793439-4ba59b27-6b66-4ec9-acef-63871520bb93.png">

**Comment by Crawron** [comment]
Fixed in #416
